name: hms_room_kit
description: 100ms Room Kit provides simple & easy to use UI components to build Live Streaming & Video Conferencing experiences in your apps.
version: 1.1.3
homepage: https://www.100ms.live/
repository: https://github.com/100mslive/100ms-flutter
issue_tracker: https://github.com/100mslive/100ms-flutter/issues
documentation: https://www.100ms.live/docs

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  hmssdk_flutter: 1.10.3
  intl: ^0.18.0
  permission_handler: ^11.0.0
  provider: ^6.0.5
  google_fonts: 6.1.0
  draggable_widget: ^2.0.0
  badges: ^3.1.1
  shared_preferences: ^2.2.0
  lottie: ^2.3.2
  flutter_svg: ^2.0.5
  path_provider: ^2.0.15
  dropdown_button2: ^2.1.4
  focus_detector_v2: ^3.1.0+1
  flutter_linkify: ^6.0.0
  tuple: ^2.0.2
  url_launcher: ^6.1.11
  share_plus: ^7.0.2
  collection: ^1.17.0
  dots_indicator: ^3.0.0
  webview_flutter: ^4.5.0
  pointer_interceptor: ^0.10.1
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/src/assets/
    - lib/src/assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
